### ISSUE TITLE
Graphviz and Course v4 Notebooks

### ISSUE THREAD

**Issue by chusc123** [fastai/docker-containers#16]
I'm using these containers to follow along with the v4 course and had the following issues:

1.  Graphviz is not included.  If you use the v4 course notebooks, you get an error to install graphviz.  Please consider adding this to the image.  I have to open a terminal in jupyter and type conda install graphviz every time to get the notebooks to work.
2.  Previous course notebooks are included not current course notebooks.  This container should include the commented notebooks here:  https://github.com/fastai/fastbook and the uncommented notebooks here:  https://github.com/fastai/course-v4 instead of the course v3 notebooks.

**Comment by hamelsmu** [comment]
Added it just for you 

![image](https://user-images.githubusercontent.com/1483922/91119819-0fc82f00-e649-11ea-9012-3280a3bd9a0f.png)
