### ISSUE TITLE
course-v4 and fastbook folders inside fastcore

### ISSUE THREAD

**Issue by ravimulpuri** [fastai/docker-containers#19]
Hi,

In the `fastdotai/fastai-course` docker image, the `course-v4` and `fastbook` folders are located inside the `fastcore` directory instead of `/workspace` directory.

If the decision is to keep the folders inside the `fastcore`, then please close this issue.

If not, the issue is because of this line in the dockerfile located in fastai-build
```bash
RUN /bin/bash -c "if [[ $BUILD == 'course' ]] ; then echo \"Course Build\" && cd fastai && pip install . && cd ../fastcore && pip install . && git clone https://github.com/fastai/fastbook --depth 1 && git clone https://github.com/fastai/course-v4 --depth 1; fi"
RUN echo '#!/bin/bash\njupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser' >> run_jupyter.sh
COPY download_testdata.py ./
COPY extract.sh ./
RUN chmod u+x extract.sh
RUN chmod u+x run_jupyter.sh
```

After the pip install of `fastcore` library, the script doesn't navigate to `workspace` directory. I can make the change and raise a PR if you think this is an issue

Thanks
Ravi

**Comment by hamelsmu** [comment]
Yes please make the change
