### ISSUE TITLE
CUDA broken?

### ISSUE THREAD

**Issue by traverst** [fastai/docker-containers#42]
Hi

I recently updated my docker image to use the latest build (March 2021) Docker image and it seems to have killed my CUDA (11.3).   I am able to run fastai inside docker but it complains that that pytorch hasn't been compiled for CUDA.

I checked to see if cuda was available and it is no longer working with the (March 2021) build.

My previous docker image works and I check the previous version (Dec 2020) and they are working fine.

There are a few changes in the new version 
- replacing the pytorch/pytorch with fastai/fastai (imports).   
- apt-get  and pip removal.

I am using Amy-Tabb's docker file that builds on the fastdotai dockerfile.

I was wondering if you could provide some advice on what may be happening.  

Thanks

**Comment by traverst** [comment]
I have worked this out.

Some experimentation building different version of the Dockerfile (Nvidia Driver 465.19.01, CUDA V 11.3):

Fastdotai/fastai:2020-10-02, FastAI Version: 2.0.16, Torch 1.6.0, cuda available yes, cuDNN 7603
Fastdotai/fastai:2021-02-11, FastAI Version: 2.2.5, Torch 1.7.1, cuda available yes, cuDNN 8005
Fastdotai/fastai:latest, FastAI Version: 2.3.1, Torch 1.8.1+cpu, cuda available no

I have a 3090 RTX so I need Torch 1.7+ but Fastai isn't current working with Torch 1.8+ so I can use the 2021-02-11 for now!
Except that version of Fastai as the slow epoch bug.... so will need to see if I can get a newer version of fastai that doesn't use 1.8.

**Comment by marii-moe** [comment]
Yeah I have the exact same issue, admittedly had been pip installing things inside my containers for a bit, but decided to update as I ran into issues managing dependencies.

**Comment by marii-moe** [comment]
Actually noticed that the change to remove cuda from fastai-dev was pushed 3 hours ago: https://hub.docker.com/r/fastdotai/fastai-dev/tags?page=1&ordering=last_updated

**Comment by jph00** [comment]
@hamelsmu do you know how CUDA got removed? Was it intentional? Can it be put back?

(I'm only familiar with the fastai namespace stuff, which is mainly for CI. I prefer to use conda for setting up my own environment, instead of docker.)

**Comment by traverst** [comment]
Just a note on docker rational.  I have a circumstance where my machine is not connected to the internet (ever) and through docker I can still use fastai on that machine.  Amy Tabb also has a different use case that means she likes to use docker too.
(end of page  https://amytabb.com/ts/2020-09-19/)

**Comment by hamelsmu** [comment]
Thanks for letting me know, it might take me a week or so before I can properly dig into this will let you know what I find

**Comment by traverst** [comment]
Let me know if there is anything I can do to help!

**Comment by hamelsmu** [comment]
I have not forgot about this, but I haven't had the chance to get to it yet.  I'm hoping to take a look later this week.  In the meantime if anyone is able to work out what the minimal fix would be please do share.

**Comment by hamelsmu** [comment]
This happened because we switched to inheriting from the main `fastai` images instead of building our own for consistency.  https://github.com/fastai/docker-containers/blame/master/fastai-build/Dockerfile#L2

Installing CUDA is one of the things I hate the most to be honest.  I can revert this back to inheriting from the official PyTorch image that has CUDA support.

**Comment by traverst** [comment]
Thanks for that.   I couldn't find the code for the fastai dockerfile (image).  I previously did a manual build with the old dockerfile (pytorch version) which worked for me.   One thing is that I ended up with a 9 GB image but that is probably some docker magic I missed!.

**Comment by hamelsmu** [comment]
The image will probably be large, but at least this will unblock you.
