### ISSUE TITLE
How to get PyTorch 1.8 supported fastai docker image

### ISSUE THREAD

**Issue by harishanand95** [fastai/docker-containers#61]
Hi, 

I tried pulling fastdotai/fastai:2021-02-11 which gave 1.7.1 version, while trying the latest tag version gave torch 1.10.0

Are there any tags that can be used to get 1.8 version specifically?

Command:
`docker run --gpus 1 fastdotai/fastai:2021-02-11 python -c "import torch;print(torch.__version__)"`

Thank you!

**Comment by jph00** [comment]
I don't think so.
